### ISSUE TITLE
[Design] Shutdown Server Use Case

### ISSUE THREAD

**Issue by AlekseyPanas** [CSC207-2022F-UofT/course-project-team-tree-dog#23]
Core Directives:
- Design work will be done in the clean arch doc
- Additional logic written in existing class boxes must be in the designated color
- Removing logic in existing class boxes must be done by putting a strikethrough and changing to the designated color
- Any new class boxes added must have a min 2px outline in the designated color. The text inside this box doesn’t need to be in the designated color.
- Any other complex modifications (such as moving or removing existing arrows) should not be done. Instead, make a text box with the designated color outline and write these desired modifications there

<hr></hr>

Use case to shut down the server gracefully. Can be called at ANY time from the View. When executed, should terminate all threads gracefully. There is no need to worry about saving the stories or game states (those would be considered separate features for later). 

<h4>Color: </h4>

![Image](https://user-images.githubusercontent.com/47086586/202069046-7c4bce22-5f48-443c-929c-fee25aac0c05.png)

**Comment by Serdiuk-Andrii** [comment]
The first version of the design has been added to the diagram. Now it contains some code repetition that can probably be avoided by creating a base class for interruptable threads, a universal output data like ShutdownServerOutputData, the base class for all the output boundaries, and the base class for the output data

**Comment by Serdiuk-Andrii** [comment]
The second version of the design has been added
