### ISSUE TITLE
[Misc] Thread Safety Use Case Architecture

### ISSUE THREAD

**Issue by AlekseyPanas** [CSC207-2022F-UofT/course-project-team-tree-dog#44]
Any time you engage with locks, use the structure as depicted by (B) in [this](https://stackoverflow.com/questions/4664717/how-would-we-use-try-finally-for-lock-lock-and-lock-unlock) StackOverflow Post. That is, engage the lock. Then put any code you are writing that will execute while your desired data is locked into the `try` block. Unlock inside the `finally` block. The `finally` block ensures that if your code crashes on that thread, the lock will be released so it doesn't cause a deadlock for other threads.

<hr></hr>

**Player Pool**
- Create a `ReentrantLock` attribute in `LobbyManager` intended for the player pool (name it appropriately)
- `addPlayerToPool` method in `LobbyManager` should lock for the `playerPool.add` call. Add to the javadoc saying that this method engages pool lock
- In `SpInteractor.SpTask` lock for the entire run method
- In `DcInteractor.DcThread` Lock pool for the duration of `removeFromPoolCancel`

<hr></hr>

**JplThread hasCancelled and game**
- Create a `ReentrantLock` attribute in `JplThread` intended for `JplThread.hasCancelled` and `JplThread.game`
- From the lock, get a new condition variable and also assign it to an attribute
- In `JplThread` while loop, remove the spin wait call and instead call `condition.await()`. Engage the lock before the loop and put the loop as well as the following `if``else` blocks into a try block. unlock at the end inside a finally block. Inside `onJoinGamePlayer` and `onCancelPlayer` signal the condition variable.
- In `SpInteractor.SpTask` lock before `removeFromPoolJoin` and `removeAllFromPoolJoin` each, and unlock right after.
- In `DcInteractor.DcThread` lock for the execution of `removeFromPoolCancel`
- Add to Javadoc for `removeFromPoolCancel`, `removeFromPoolJoin`, and their "All" variants saying that they are not thread safe. The reason for this is because the locks are engaged in a more complex manner than simply for the duration of these methods

<hr></hr>

**Game**
- Create a `ReentrantLock` attribute in `LobbyManager` intended for `LobbyManage.game`
- In `SpInteractor.SpTask`, lock for the entire run method
- In `DcInteractor.DcThread` lock for the duration of the `removePlayerFromGame` call
- In `SwInteractor.SwThread` lock for the duration of the entire `run` method.
- In `RgInteractor.RgTask` lock for the duration of the entire `run` method
- In `JplInteractor.JplThread` lock during the `GameDTO.fromGame` call to avoid game state from changing while reading the game

<hr></hr>

Any object variables shared across threads must be declared `volatile`. This ensures that java knows that these variables are subject to change from other threads so that it checks the value each time rather than optimizing. Note that `volatile` only affects the variable reference. That is, for `m.game` as an example, `volatile` will ensure java checks whether `m.game` is `null` or is set to a value. It WILL NOT automatically declare all instance attributes of this object as also being `volatile`. You must trace into `m.game` and see which particular attributes are being modified / read across threads and declare those `volatile` as well.

**Comment by Serdiuk-Andrii** [comment]
> Create a ReentrantLock attribute in JplThread intended for JplThread.hasCancelled and JplThread.game

If the lock is created for every player (which is good for performance), we need to share this lock with other instances like DcInteractor and SpInteractor

**Comment by Serdiuk-Andrii** [comment]
> In SpInteractor.SpTask lock before removeFromPoolJoin and removeAllFromPoolJoin each, and unlock right after.

We need to lock this whole section with removeFromPoolJoin to avoid race conditions. For instance, for some time, a player can be present in the pool and in the game at the same time (when we sort them into the game). If we do not use locks, the player may disconnect from the game before we remove them from the pool in SpInteractor

**Comment by Serdiuk-Andrii** [comment]
[https://drive.google.com/file/d/1rKEZoQHdyUC37gerlGeuFN6z6WxP6pIx/view?usp=share_link](url) — if we follow this rule, everything will be fine
