### ISSUE TITLE
[Bug] DcInteractorTests concurrency errors

### ISSUE THREAD

**Issue by AlekseyPanas** [CSC207-2022F-UofT/course-project-team-tree-dog#56]
**Replicate:** If you run the DcInteractorTests repeatedly, testDisconnectPlayerFromPool will randomly give one of three outcomes. The test may pass, the test may throw a ConcurrentModificationExample, or the test may throw a NoSuchElementException.

**Comment by Serdiuk-Andrii** [comment]
The bug was fixed in the corresponding branch
